import AllProvider from "@/providers/AllProvider";
import NextThemeProvider from "@/providers/NextThemeProvider";
import { ChildrenProps } from "@/types/ChildrenProps";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Speed Xpress",
  description: "Generated by Speed Xpress Team",
};

export default function RootLayout({ children }: ChildrenProps) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen bg-light dark:bg-dark`}>
        <AllProvider>
          <NextThemeProvider>
            <div className="text-dark dark:text-light bg-light dark:bg-dark">
              {children}
            </div>
          </NextThemeProvider>
        </AllProvider>
      </body>
    </html>
  );
}
