import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeSwitcher } from "@/components/ThemeSwitcher/ThemeSwitcher";
import { ChildrenProps } from "@/types/ChildrenProps";
import NextThemeProvider from "@/providers/NextThemeProvider";
import AllProvider from "@/providers/AllProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Speed Xpress",
  description: "Generated by Speed Xpress Team",
};

export default function RootLayout({ children }: ChildrenProps) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen bg-light dark:bg-dark`}>
        <AllProvider>
          <NextThemeProvider>
            <div className="text-dark dark:text-light bg-light dark:bg-dark">
              {/* <div className="fixed right-0 z-50 p-4">
                <ThemeSwitcher />
              </div> */}
              {children}
            </div>
          </NextThemeProvider>
        </AllProvider>
      </body>
    </html>
  );
}
