import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import NextThemeProvider from "@/providers/NextThemeProvider"
import { ThemeSwitcher } from "@/components/ThemeSwicher/ThemeSwicher"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Speed Xpress",
  description: "Generated by Speed Xpress Team",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <NextThemeProvider>
          <div className="h-screen bg-light dark:bg-dark dark:text-light text-dark">
            <div className="absolute right-0 inset-y-0 z-50 p-4">
              <ThemeSwitcher />
            </div>
            {children}
          </div>
        </NextThemeProvider>
      </body>
    </html>
  )
}
